import_from_git(
  url: "https://github.com/tinkoff-mobile-tech/workflows.git", # The URL of the repository to import the Fastfile from.
  path: "fastlane/Fastfile" # The path of the Fastfile in the repository.
)
